// <auto-generated />
namespace NKKhoan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class themchưcvu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(themchưcvu));
        
        string IMigrationMetadata.Id
        {
            get { return "202111121609567_themchưcvu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
